2024-04-19 03:00:22,513 - ERROR - An error occurred: division by zero
Traceback (most recent call last):
  File "d:\logging\logging_test.py", line 22, in example_function
    result = 10 / 0
             ~~~^~~
ZeroDivisionError: division by zero
